adx_contentdisposition: 756150000
adx_enabletracking: false
adx_excludefromsearch: false
adx_hiddenfromsitemap: false
adx_name: product-service-3.png
adx_parentpageid: 063da65b-cee2-4805-8f00-220cf89ead47
adx_partialurl: product-service-3.png
adx_publishingstateid: 4d4e82c7-4173-4a0d-865b-394884d0a202
adx_webfileid: 019d33c1-ef92-4f18-8b9a-1d01b079d287
annotationid: 7ea5f71c-0030-f011-8c4d-7c1e525d4b79
filename: product-service-3.png
isdocument: true
mimetype: image/png
objectid: 019d33c1-ef92-4f18-8b9a-1d01b079d287
objecttypecode: adx_webfile
